### PR TITLE
merge trachoma_functions.py from NTD repo

### PR DESCRIPTION
**Pull request by igorclark**
This PR pulls in the recent changes from the `trachoma_functions.py` in the NTD repo.

### CODE REVIEW

**Comment by tlestang** [comment]
Hello!

**Review by mattg3004 — COMMENTED** [review]
won't need the import datetime and matplotlib i would guess.

the bulk of the changes are at the beginning of the code and to do with transitions between compartments of the model. All of these seem reasonable, though I'm unable to really judge if any differences with the initial version are 'correct'. Anna and Simon said that this was a version which was working as it was wanted, so I would defer to their judgement on this.

the only other substantive change is to the D_period_function, which has a tweaked output. i made this change to match Anna's R function, and the results all matched with her model, so assume this is correct.

the change at the bottom of the file adds the ability to output prevalence data stratified by age, which is necessary for endgame project

all other changes are cosmetic i think

so seems fine to me

**Comment by igorclark** [comment]
Thanks @mattg3004. One thing I've just noticed is that this reverts the [OxRSE 'bisect replacement'](https://github.com/ArtRabbitStudio/ntd-model-trachoma/commit/75844ba42db41a0b9f94776a519a14c13537d4ce) change - should that still be in there @tlestang?

**Comment by tlestang** [comment]
Good catch @igorclark :eagle: 

I guess the file was overwritten by the other repo's version that didn't have these changes and git can't pick it up as a conflict.

I simply reapplied the changes. Feel free to press the green button.

**Review by drsimonspencer — COMMENTED** [review]
Maybe delete the comment line 44? It is now lines 65 and 66 that prevent the spiral of doom. Line 44 is not needed.

**Pull request merged**
